<div class="grid gap-4 md:grid-cols-2">
    <label class="field-label">Nombre<input class="field-input" name="name" value="{{ old('name', $profile->name) }}" required placeholder="B1000 puerto 10"></label>
    <label class="field-label">Conector TTI/MQTT<select class="field-input" name="connector_id" required>@foreach($connectors as $connector)<option value="{{ $connector->id }}" @selected(old('connector_id', $profile->connector_id) === $connector->id)>{{ $connector->name }}</option>@endforeach</select></label>
    @php($selectedProducts = collect(old('product_ids', $profile->exists ? $profile->products->pluck('id')->all() : [])))
    <label class="field-label">Productos cubiertos<select class="field-input" name="product_ids[]" multiple size="6">@foreach($products as $product)<option value="{{ $product->id }}" @selected($selectedProducts->contains($product->id))>{{ $product->name }}</option>@endforeach</select><span class="mt-1 block text-xs font-normal text-slate-400">Selecciona todos los productos que usan este formato. Ctrl/Cmd permite elegir cuatro o más. Sin selección, el perfil es genérico.</span></label>
    <label class="field-label">Prioridad<input class="field-input" type="number" name="priority" min="1" max="1000" value="{{ old('priority', $profile->priority ?? 100) }}" required><span class="mt-1 block text-xs font-normal text-slate-400">El número menor se evalúa primero.</span></label>
    <label class="field-label">FPort para reconocerlo<input class="field-input" type="number" name="match_f_port" min="1" max="255" value="{{ old('match_f_port', $profile->match_f_port) }}" placeholder="10"></label>
    <label class="field-label">Ruta discriminadora<input class="field-input font-mono" name="match_path" value="{{ old('match_path', $profile->match_path) }}" placeholder="message.type"></label>
    <label class="field-label">Valor discriminador<input class="field-input font-mono" name="match_value" value="{{ old('match_value', $profile->match_value) }}" placeholder="ble_scan"></label>
    <label class="field-label">Ruta del receptor<input class="field-input font-mono" name="receiver_path" value="{{ old('receiver_path', $profile->receiver_path) }}" placeholder="scanner.id"><span class="mt-1 block text-xs font-normal text-slate-400">Opcional; relativa a decoded_payload.</span></label>
    <label class="field-label">Ruta de la lista de lecturas<input class="field-input font-mono" name="observations_path" value="{{ old('observations_path', $profile->observations_path ?? 'data.readings') }}" required placeholder="data.readings"></label>
    <div class="grid grid-cols-2 gap-3"><label class="field-label">Campo MAC<input class="field-input font-mono" name="mac_path" value="{{ old('mac_path', $profile->mac_path ?? 'address') }}" required></label><label class="field-label">Campo RSSI<input class="field-input font-mono" name="rssi_path" value="{{ old('rssi_path', $profile->rssi_path ?? 'signal') }}" required></label></div>
    <label class="field-label md:col-span-2"><span class="flex items-center gap-2"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $profile->enabled))> Perfil activo</span></label>
</div>
