@extends('layouts.app')
@section('title', $connector->name)
@section('heading', 'Estado del conector')
@section('content')
    <div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><a class="text-sm text-brand-primary" href="{{ route('connectors.index') }}">← Todos los conectores</a><h2 class="mt-2 text-xl font-semibold text-slate-950">{{ $connector->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $definition['name'] }} · {{ $connector->kind->label() }}</p></div><div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('connectors.test', $connector) }}">@csrf<button class="btn-secondary">Probar</button></form><form method="POST" action="{{ route('connectors.toggle', $connector) }}">@csrf<button class="btn-primary">{{ $connector->status->value === 'active' ? 'Desactivar' : 'Activar' }}</button></form>@if($connector->status->value !== 'active')<form method="POST" action="{{ route('connectors.destroy', $connector) }}" onsubmit="return confirm('¿Eliminar definitivamente este conector y todos sus eventos asociados?')">@csrf @method('DELETE')<button class="btn-secondary text-red-600">Eliminar</button></form>@endif</div></div>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-5">@foreach([['Estado', $connector->status->label()], ['Eventos recibidos', $connector->telemetry_events_count], ['Procesados', $connector->processed_events_count], ['Pendientes', $connector->pending_events_count], ['Fallidos', $connector->failed_events_count]] as $metric)<article class="metric-card"><p class="text-sm text-slate-500">{{ $metric[0] }}</p><p class="mt-2 text-2xl font-semibold">{{ $metric[1] }}</p></article>@endforeach</div>
    @if($connector->provider->value === 'mqtt')<section class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><h3 class="font-semibold">Operación MQTT</h3><p class="mt-1">Activar habilita la configuración, pero el listener debe permanecer ejecutándose en el servidor.</p><code class="mt-3 block overflow-x-auto rounded-lg bg-slate-900 p-3 text-xs text-white">php artisan loratrack:mqtt-listen {{ $connector->id }}</code><p class="mt-2 text-xs">Supervísalo con Supervisor o systemd. Host: {{ $connector->configuration['host'] ?? '—' }} · Topic: {{ $connector->configuration['topic'] ?? '—' }}</p></section>@endif
    @include('connectors.partials.guide', ['connector' => $connector])
    @if($connector->last_error)<div class="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>Último error:</strong> {{ $connector->last_error }}</div>@endif
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <section class="panel"><div class="panel-header"><div><h2 class="panel-title">Log operacional</h2><p class="panel-subtitle">Inicio, conexión, mensajes y errores</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Nivel</th><th>Evento</th><th>Detalle</th></tr></thead><tbody>@forelse($logs as $log)<tr><td class="whitespace-nowrap">{{ $log->created_at->format('d-m-Y H:i:s') }}</td><td>{{ strtoupper($log->level) }}</td><td>{{ $log->event }}</td><td>{{ $log->message }}</td></tr>@empty<tr><td colspan="4">Todavía no hay actividad registrada.</td></tr>@endforelse</tbody></table></div></section>
        <section class="panel"><div class="panel-header"><div><h2 class="panel-title">Telemetría reciente</h2><p class="panel-subtitle">Últimos 100 eventos recibidos</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Recepción</th><th>Estado</th><th>Dispositivo</th><th>Error</th></tr></thead><tbody>@forelse($events as $event)<tr><td class="whitespace-nowrap">{{ $event->received_at->format('d-m-Y H:i:s') }}</td><td><span class="status-badge status-{{ $event->processing_status === 'processed' ? 'active' : ($event->processing_status === 'failed' ? 'error' : 'disabled') }}">{{ $event->processing_status }}</span></td><td>{{ $event->device?->name ?? data_get($event->raw_payload, 'end_device_ids.device_id', '—') }}</td><td class="text-xs text-red-600">{{ Str::limit($event->processing_error, 100) }}</td></tr>@empty<tr><td colspan="4">No se ha recibido telemetría.</td></tr>@endforelse</tbody></table></div></section>
    </div>
@endsection
